---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: edit-power-dev-dev
  namespace: quarkus-dev
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: power-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: jpl-user

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: edit-power-dev-prod
  namespace: quarkus-prod
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: power-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: jpl-user

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: edit-regular-dev-dev
  namespace: quarkus-dev
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: regular-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: jpl-user