---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: edit
  namespace: springboot-dev
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: power-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: edit
  namespace: springboot-prod
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: power-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: edit
  namespace: springboot-dev
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: regular-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit