kind: Deployment
apiVersion: apps/v1
metadata:
  name: my-java-quarkus
  labels:
    version: "1.0"
    app.openshift.io/runtime: quarkus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-quarkus-app
  template:
    metadata:
      labels:
        app: java-quarkus-app
        version: "1.0"
        app.openshift.io/runtime: quarkus
    spec:
      containers:
        - name: my-java-quarkus
          image: quay.io/rhn_support_jlevy/quarkus-jpl:latest
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              memory: "100Mi"
              cpu: "10m"
---

---
kind: Service
apiVersion: v1
metadata:
  name: my-java-quarkus-svc
spec:
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: 8443-tcp
      protocol: TCP
      port: 8443
      targetPort: 8443
  selector:
    app: java-quarkus-app

---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: quarkus-prod 
spec:
  host: my-java-quarkus.apps.ocp.jpl.ovh 
  to:
    kind: Service
    name: my-java-quarkus-svc 
  port:
    targetPort: 8080-tcp
  tls:
    termination: edge
  wildcardPolicy: None
