---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infra
  namespace: openshift-gitops
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - name: in-cluster
      namespace: '*'
      server: 'https://kubernetes.default.svc'
  sourceRepos:
    - 'https://github.com/jeanphilippelevy/openshift-cicd'

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rbac
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: 'https://kubernetes.default.svc'
  project: infra
  source:
    path: devfile-sample-java-springboot-basic/rbac
    repoURL: 'https://github.com/jeanphilippelevy/openshift-cicd'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
